<?xml version="1.0"?>
<robot name="dp_robot" xmlns:xacro="http://www.ros.org/wiki/xacro">

  <gazebo>
    <plugin name="differential_drive_controller" filename="libgazebo_ros_diff_drive.so">
        <alwaysOn>true</alwaysOn>
        <updateRate>20</updateRate>
        <leftJoint>joint_left_wheel</leftJoint>
        <rightJoint>joint_right_wheel</rightJoint>
        <wheelSeparation>${chassisLength}</wheelSeparation>
        <wheelDiameter>${wheelRadius*2}</wheelDiameter>
        <wheelTorque>6.5</wheelTorque>
        <commandTopic>cmd_vel</commandTopic>
        <odometryTopic>odom</odometryTopic>
        <odometryFrame>odom</odometryFrame>
        <robotBaseFrame>link_chassis</robotBaseFrame>
    </plugin>
  </gazebo>

  <gazebo reference="link_kinect_sensor">
    <sensor name="sensor_kinect_camera" type="depth">
      <update_rate>20</update_rate>
      <camera>
        <horizontal_fov>1.047198</horizontal_fov>
        <image>
          <width>640</width>
          <height>480</height>
          <format>R8G8B8</format>
        </image>
        <clip>
          <near>0.05</near>
          <far>5</far>
        </clip>
      </camera>
      <plugin name="sensor_kinect_controller" filename="libgazebo_ros_openni_kinect.so">
        <baseline>0.2</baseline>
        <alwaysOn>true</alwaysOn>
        <updateRate>1.0</updateRate>
        <cameraName>kinect</cameraName>
        <imageTopicName>/kinect/color/image_raw</imageTopicName>
        <cameraInfoTopicName>/kinect/color/camera_info</cameraInfoTopicName>
        <depthImageTopicName>/kinect/depth/image_raw</depthImageTopicName>
        <depthImageInfoTopicName>/kinect/depth/camera_info</depthImageInfoTopicName>
        <pointCloudTopicName>/kinect/depth/points</pointCloudTopicName>
        <frameName>link_gazebo_kinect_frame</frameName>
        <pointCloudCutoff>0.5</pointCloudCutoff>
        <pointCloudCutoffMax>3.0</pointCloudCutoffMax>
        <distortionK1>0.00000001</distortionK1>
        <distortionK2>0.00000001</distortionK2>
        <distortionK3>0.00000001</distortionK3>
        <distortionT1>0.00000001</distortionT1>
        <distortionT2>0.00000001</distortionT2>
        <CxPrime>0</CxPrime>
        <Cx>0</Cx>
        <Cy>0</Cy>
        <focalLength>0</focalLength>
        <hackBaseline>0</hackBaseline>
      </plugin>
    </sensor>
  </gazebo>

  <gazebo>
    <plugin name="gazebo_ros_imu_controller" filename="libgazebo_ros_imu.so">
      <robotNamespace></robotNamespace> <!--empty to only publish /imu/data instead /robot/imu/data-->
      <topicName>imu/data</topicName>
      <serviceName>imu/service</serviceName>
      <bodyName>link_chassis</bodyName>
      <gaussianNoise>0</gaussianNoise>
      <rpyOffsets>0 0 0</rpyOffsets>
      <updateRate>10.0</updateRate>
      <alwaysOn>true</alwaysOn>
      <gaussianNoise>0</gaussianNoise>
    </plugin>
  </gazebo>
</robot>
